name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: id-dci-web1986.main-hosting.eu
          username: u267562440
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd domains/family.seqra.space/public_html
            git pull origin main
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
